### ISSUE TITLE
Counter Handling Error

### ISSUE THREAD

**Issue by Zayelion** [IceYGO/ygosharp#5]
The following error prints out when the duelist attempts to add a counter to a card.

```
System.Exception: [GameAnalyser] Unhandled packet id: 0
   at YGOSharp.GameAnalyser.Analyse(GameMessage msg, BinaryReader reader, Byte[] raw)
   at OCGWrapper.Duel.HandleMessage(BinaryReader reader, Byte[] raw, Int32 len)
   at OCGWrapper.Duel.Process()
   at YGOSharp.Game.Process()
   at YGOSharp.Game.SetResponse(Byte[] resp)
   at YGOSharp.Player.OnResponse(GamePacketReader packet)
   at YGOSharp.Player.Parse(GamePacketReader packet)
   at YGOSharp.CoreServer.<>c__DisplayClass2.<AddClient>b__0(Object sender, MessageEventArgs e)
   at YGOSharp.Network.CoreClient.OnMessage(GamePacketReader message)
   at YGOSharp.Network.CoreClient.NetworkParse()
   at YGOSharp.Network.CoreClient.Update()
   at YGOSharp.CoreServer.Tick()
   at YGOSharp.Program.Main(String[] args)
```

**Comment by Zayelion** [comment]
Never mind error on my part.
